name: Floating Tags
# This workflow manages floating tags for this project. When digests
# change in ./containertags/* files, the associated tag is synced
# in the container registry.
on:
  push: # Includes when PRs get merged to the branches.
    branches:
      - "main"
jobs:
  move-tag-ghactions:
    name: "Update Tag: latest"
    uses: ./.github/workflows/manage-floating-tag.yaml
    with:
      tag: latest
    secrets:
      REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      IMAGE_REGISTRY: ${{ secrets.IMAGE_REGISTRY }}